[package]
name = "nightfall-fx"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_state.workspace = true
enum_dispatch.workspace = true
orx-parallel.workspace = true
nightfall = { path = "../common" }
nightfall-compositor = { path = "../compositor" }
nightfall-dmx = { path = "../dmx" }
nightfall-engine = { path = "../engine" }
nightfall-fixtures = { path = "../fixtures" }
nightfall-instances = { path = "../instances" }
nightfall-playback-planner = { path = "../playback-planner" }
nightfall-cmd-parse = { path = "../cmd-parse" }
nightfall-selection = { path = "../selection" }
nightfall-undo = { path = "../undo" }
nightfall-waveform = { path = "../waveform" }
thiserror = "2.0"
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
smart-default.workspace = true
tracing.workspace = true
typeshare.workspace = true
uuid.workspace = true

[dev-dependencies]
moonshine-kind.workspace = true
nightfall-desk = { path = "../desk" }
nightfall-clips = { path = "../clips" }
nightfall-flow = { path = "../flow" }
nightfall-fx-module = { path = "../fx-module" }

[lints]
workspace = true
