// SPDX-License-Identifier: MPL-2.0

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

//! Runtime timeline action recording.

use std::collections::{HashMap, HashSet};
use std::time::Duration;

use bevy_ecs::prelude::*;
#[cfg(test)]
use nightfall_clips::Clip;
use nightfall_clips::{ClipAction, ClipLookup, ClipLookupSnapshot};
use nightfall_engine::prelude::{
    CommandEnvelope, DynEngineActionEnvelope, EngineActionEnvelope, OperationId,
    PendingEngineActionBuffer, UndoId,
};
use nightfall_timecode::prelude::{TimecodeEvent, TimecodeGenerator};
use uuid::Uuid;

use crate::components::MaterializedTimeline;
use crate::prelude::{Action, ActionKind, TimelineAction, TimelineCommand};

/// Runtime recording state for one timeline.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[typeshare::typeshare]
pub struct TimelineRecordingState {
    /// User-facing timeline ID.
    pub timeline_id: u32,
    /// Whether the timeline is armed for recording.
    pub enabled: bool,
    /// Track that receives recorded actions.
    pub target_track_id: Option<String>,
}

/// Runtime recording state for all timelines.
#[derive(Resource, Default, Debug, Clone)]
pub struct TimelineRecordingStates {
    states: HashMap<u32, TimelineRecordingState>,
}

impl TimelineRecordingStates {
    /// Set the full recording state for a timeline.
    pub fn set(&mut self, timeline_id: u32, enabled: bool, target_track_id: Option<String>) {
        self.states.insert(
            timeline_id,
            TimelineRecordingState {
                timeline_id,
                enabled,
                target_track_id,
            },
        );
    }

    /// Set only the target track for a timeline, preserving enabled state.
    pub fn set_target_track(&mut self, timeline_id: u32, target_track_id: Option<String>) {
        let state = self
            .states
            .entry(timeline_id)
            .or_insert(TimelineRecordingState {
                timeline_id,
                enabled: false,
                target_track_id: None,
            });
        state.target_track_id = target_track_id;
    }

    /// Disable recording for a timeline while preserving the selected target track.
    pub fn disable(&mut self, timeline_id: u32) {
        let state = self
            .states
            .entry(timeline_id)
            .or_insert(TimelineRecordingState {
                timeline_id,
                enabled: false,
                target_track_id: None,
            });
        state.enabled = false;
    }

    /// Remove all runtime state for a timeline.
    pub fn remove(&mut self, timeline_id: u32) {
        self.states.remove(&timeline_id);
    }

    /// Return the state for a timeline.
    pub fn get(&self, timeline_id: u32) -> Option<&TimelineRecordingState> {
        self.states.get(&timeline_id)
    }

    /// Return all states sorted by timeline ID for stable websocket output.
    pub fn sorted_states(&self) -> Vec<TimelineRecordingState> {
        let mut states = self.states.values().cloned().collect::<Vec<_>>();
        states.sort_by_key(|state| state.timeline_id);
        states
    }
}

/// Runtime identities generated by timeline playback itself.
#[derive(Resource, Default, Debug)]
pub struct TimelineCommandOrigins {
    clip_undo_ids: HashSet<Uuid>,
    clip_operation_ids: HashSet<OperationId>,
}

impl TimelineCommandOrigins {
    /// Mark a legacy clip undo identity as timeline-originated.
    pub fn mark_clip_undo_id(&mut self, undo_id: Uuid) {
        self.clip_undo_ids.insert(undo_id);
    }

    /// Whether a legacy clip undo identity was generated by timeline playback.
    pub fn is_timeline_clip_undo_id(&self, undo_id: Uuid) -> bool {
        self.clip_undo_ids.contains(&undo_id)
    }

    /// Mark a concrete clip action as timeline-originated.
    pub fn mark_clip_operation_id(&mut self, operation_id: OperationId) {
        self.clip_operation_ids.insert(operation_id);
    }

    /// Whether a concrete clip action was generated by timeline playback.
    pub fn is_timeline_clip_operation_id(&self, operation_id: OperationId) -> bool {
        self.clip_operation_ids.contains(&operation_id)
    }

    /// Clear all recorded origins after the recorder has consumed this frame.
    pub fn clear(&mut self) {
        self.clip_undo_ids.clear();
        self.clip_operation_ids.clear();
    }
}

/// In-progress recording state for one timeline capture session.
#[derive(Debug, Clone)]
struct TimelineRecordingSession {
    target_track_id: String,
    actions: Vec<Action>,
}

/// Actions staged by an active recording session for one timeline.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[typeshare::typeshare]
pub struct TimelineRecordingPreview {
    /// User-facing timeline ID.
    pub timeline_id: u32,
    /// Track that receives recorded actions.
    pub target_track_id: String,
    /// Actions captured so far in the active recording session.
    pub actions: Vec<Action>,
}

/// Recorded actions accumulated for active recording sessions.
#[derive(Resource, Default, Debug)]
pub struct TimelineRecordingSessions {
    sessions: HashMap<u32, TimelineRecordingSession>,
}

impl TimelineRecordingSessions {
    fn target_track_id_for(
        &mut self,
        timeline_id: u32,
        target_track_id: Option<&str>,
        recording_states: &mut TimelineRecordingStates,
    ) -> String {
        if let Some(session) = self.sessions.get(&timeline_id) {
            return session.target_track_id.clone();
        }

        let track_id = target_track_id
            .map(str::to_string)
            .unwrap_or_else(|| format!("recorded-actions-{}", Uuid::new_v4().simple()));

        recording_states.set_target_track(timeline_id, Some(track_id.clone()));
        self.sessions.insert(
            timeline_id,
            TimelineRecordingSession {
                target_track_id: track_id.clone(),
                actions: Vec::new(),
            },
        );
        track_id
    }

    fn append_actions(&mut self, timeline_id: u32, target_track_id: String, actions: Vec<Action>) {
        self.sessions
            .entry(timeline_id)
            .or_insert(TimelineRecordingSession {
                target_track_id,
                actions: Vec::new(),
            })
            .actions
            .extend(actions);
    }

    fn take(&mut self, timeline_id: u32) -> Option<TimelineRecordingSession> {
        self.sessions.remove(&timeline_id)
    }

    pub fn remove(&mut self, timeline_id: u32) {
        self.sessions.remove(&timeline_id);
    }

    fn target_changed(&self, timeline_id: u32, target_track_id: Option<&str>) -> bool {
        let Some(session) = self.sessions.get(&timeline_id) else {
            return false;
        };
        target_track_id != Some(session.target_track_id.as_str())
    }

    /// Return all active session previews sorted by timeline ID for stable websocket output.
    pub fn sorted_previews(&self) -> Vec<TimelineRecordingPreview> {
        let mut previews = self
            .sessions
            .iter()
            .map(|(timeline_id, session)| TimelineRecordingPreview {
                timeline_id: *timeline_id,
                target_track_id: session.target_track_id.clone(),
                actions: session.actions.clone(),
            })
            .collect::<Vec<_>>();
        previews.sort_by_key(|preview| preview.timeline_id);
        previews
    }
}

/// Writes a detached clip action and marks it as timeline-originated.
pub fn write_timeline_clip_action(
    writer: &mut MessageWriter<EngineActionEnvelope<ClipAction>>,
    origins: &mut TimelineCommandOrigins,
    action: ClipAction,
) {
    let event = EngineActionEnvelope::detached(action);
    origins.mark_clip_operation_id(event.operation_id);
    writer.write(event);
}

/// Resource identifying which timeline is currently recording clip actions.
#[derive(Clone)]
struct ActiveRecordingTimeline {
    timeline_id: u32,
    position: Duration,
    target_track_id: String,
}

/// Clip action captured with timing metadata during timeline recording.
#[derive(Clone)]
struct RecordedClipAction {
    clip_label: String,
    action: ActionKind,
}

impl RecordedClipAction {
    fn label(&self) -> String {
        match &self.action {
            ActionKind::StartClip(_) => format!("Start Clip {}", self.clip_label),
            ActionKind::StopClip(_) => format!("Stop Clip {}", self.clip_label),
            ActionKind::AdvanceSequence(_) => {
                format!("Advance Sequence {}", self.clip_label)
            }
            ActionKind::BackSequence(_) => {
                format!("Back Sequence {}", self.clip_label)
            }
            ActionKind::SetClipRate { rate, .. } => {
                format!("Set {} Rate {}", self.clip_label, rate)
            }
            ActionKind::JumpToCue { cue_index, .. } => {
                format!("Jump {} to Cue {}", self.clip_label, cue_index)
            }
            ActionKind::FireCue(_) => {
                unreachable!("recorded clip actions are created from clip commands")
            }
            ActionKind::DeskEval(_) => {
                unreachable!("recorded clip actions are created from clip commands")
            }
            ActionKind::RegisteredAction(action) => {
                format!("Registered Action {}", action.id.as_str())
            }
        }
    }
}

fn rounded_duration_millis(duration: Duration) -> Duration {
    let millis = duration.as_millis().min(u128::from(u64::MAX)) as u64;
    Duration::from_millis(millis)
}

fn create_recorded_action(position: Duration, recorded_action: &RecordedClipAction) -> Action {
    Action {
        id: format!("recorded-{}", Uuid::new_v4().simple()),
        label: recorded_action.label(),
        position: rounded_duration_millis(position),
        duration: Duration::from_millis(1000),
        action: recorded_action.action.clone(),
    }
}

fn resolve_clip_action(
    clip_id: u32,
    make_action: impl FnOnce(Uuid) -> ActionKind,
    clip_lookup: &ClipLookupSnapshot,
) -> Option<RecordedClipAction> {
    let clip = match clip_lookup.by_id(clip_id) {
        Ok((_, clip)) => clip,
        Err(error) => {
            tracing::warn!(
                clip_id,
                ?error,
                "Skipping timeline recording for missing clip"
            );
            return None;
        }
    };

    let label = if clip.identifiers.label.trim().is_empty() {
        format!("Clip {}", clip.identifiers.id)
    } else {
        clip.identifiers.label.clone()
    };

    Some(RecordedClipAction {
        clip_label: label,
        action: make_action(clip.identifiers.uid),
    })
}

fn recorded_actions_from_clip_action(
    action: &ClipAction,
    clip_lookup: &ClipLookupSnapshot,
) -> Vec<RecordedClipAction> {
    let mut actions = Vec::new();
    match action {
        ClipAction::Start(id_expr)
        | ClipAction::StartAtTiming {
            clip_id: id_expr, ..
        } => {
            for id in id_expr.expand() {
                if let Some(action) = resolve_clip_action(id, ActionKind::StartClip, clip_lookup) {
                    actions.push(action);
                }
            }
        }
        ClipAction::Stop(id_expr)
        | ClipAction::StopAtTiming {
            clip_id: id_expr, ..
        } => {
            for id in id_expr.expand() {
                if let Some(action) = resolve_clip_action(id, ActionKind::StopClip, clip_lookup) {
                    actions.push(action);
                }
            }
        }
        ClipAction::Go(id_expr) => {
            for id in id_expr.expand() {
                if let Some(action) =
                    resolve_clip_action(id, ActionKind::AdvanceSequence, clip_lookup)
                {
                    actions.push(action);
                }
            }
        }
        ClipAction::Back(clip_id) => {
            for id in clip_id.expand() {
                if let Some(action) = resolve_clip_action(id, ActionKind::BackSequence, clip_lookup)
                {
                    actions.push(action);
                }
            }
        }
        ClipAction::SetRate { clip_id, rate } => {
            for id in clip_id.expand() {
                if let Some(action) = resolve_clip_action(
                    id,
                    |uid| ActionKind::SetClipRate { uid, rate: *rate },
                    clip_lookup,
                ) {
                    actions.push(action);
                }
            }
        }
        ClipAction::Goto {
            clip_id, position, ..
        }
        | ClipAction::RenderAt {
            clip_id, position, ..
        } => {
            for id in clip_id.expand() {
                if let Some(action) = resolve_clip_action(
                    id,
                    |uid| ActionKind::JumpToCue {
                        uid,
                        cue_index: *position,
                    },
                    clip_lookup,
                ) {
                    actions.push(action);
                }
            }
        }
    }
    actions
}

fn queue_recording_session_insert(
    timeline_id: u32,
    session: TimelineRecordingSession,
    pending_actions: &mut PendingEngineActionBuffer,
) {
    if session.actions.is_empty() {
        return;
    }

    pending_actions.push(DynEngineActionEnvelope::with_context(
        OperationId::new(),
        None,
        Some(UndoId::new()),
        Box::new(TimelineAction::InsertRecordedActions {
            timeline_id,
            track_id: session.target_track_id,
            actions: session.actions,
        }),
    ));
}

/// Record externally originated clip actions into armed timelines.
pub fn record_timeline_actions_system(
    mut clip_events: MessageReader<EngineActionEnvelope<ClipAction>>,
    command_origins: Res<TimelineCommandOrigins>,
    mut recording_states: ResMut<TimelineRecordingStates>,
    mut recording_sessions: ResMut<TimelineRecordingSessions>,
    timeline_query: Query<&MaterializedTimeline>,
    timecode_query: Query<&TimecodeGenerator>,
    clip_lookup: ClipLookup,
) {
    let mut timecode_times = HashMap::new();
    for timecode in timecode_query.iter() {
        timecode_times.insert(
            timecode.timecode.identifiers.uid,
            (timecode.state.current_time, timecode.state.is_active),
        );
    }

    let mut active_recording_timelines = Vec::new();
    for timeline in timeline_query.iter() {
        let timeline_id = timeline.timeline.identifiers.id;
        let Some(state) = recording_states.get(timeline_id).cloned() else {
            continue;
        };
        if !state.enabled || !timeline.is_active {
            continue;
        }
        let Some((timecode_time, timecode_active)) =
            timecode_times.get(&timeline.timeline.timecode_uid)
        else {
            continue;
        };
        if !timecode_active {
            continue;
        }
        let target_track_id = recording_sessions.target_track_id_for(
            timeline_id,
            state.target_track_id.as_deref(),
            &mut recording_states,
        );
        active_recording_timelines.push(ActiveRecordingTimeline {
            timeline_id,
            position: timeline.get_playback_position(*timecode_time),
            target_track_id,
        });
    }

    if active_recording_timelines.is_empty() {
        for _ in clip_events.read() {}
        return;
    }

    let clip_snapshot = clip_lookup.snapshot();
    let mut recorded_actions = Vec::new();
    for event in clip_events.read() {
        if command_origins.is_timeline_clip_operation_id(event.operation_id)
            || event
                .undo_id
                .is_some_and(|undo_id| command_origins.is_timeline_clip_undo_id(undo_id.into()))
        {
            continue;
        }
        recorded_actions.extend(recorded_actions_from_clip_action(
            &event.action,
            &clip_snapshot,
        ));
    }

    if recorded_actions.is_empty() {
        return;
    }

    for active_timeline in active_recording_timelines {
        let actions = recorded_actions
            .iter()
            .map(|action| create_recorded_action(active_timeline.position, action))
            .collect::<Vec<_>>();
        recording_sessions.append_actions(
            active_timeline.timeline_id,
            active_timeline.target_track_id,
            actions,
        );
    }
}

/// Finish recording sessions when playback stops, recording is disarmed, or target changes.
pub fn finish_timeline_recording_sessions_system(
    mut timecode_events: MessageReader<TimecodeEvent>,
    mut timeline_events: MessageReader<CommandEnvelope<TimelineCommand>>,
    mut timeline_actions: MessageReader<EngineActionEnvelope<TimelineAction>>,
    mut recording_states: ResMut<TimelineRecordingStates>,
    mut recording_sessions: ResMut<TimelineRecordingSessions>,
    mut pending_actions: ResMut<PendingEngineActionBuffer>,
) {
    let mut finish_timeline_ids = HashSet::new();
    let mut disable_timeline_ids = HashSet::new();

    for event in timecode_events.read() {
        match event {
            TimecodeEvent::Paused(timeline_id) | TimecodeEvent::Stopped(timeline_id) => {
                finish_timeline_ids.insert(*timeline_id);
                disable_timeline_ids.insert(*timeline_id);
            }
            TimecodeEvent::Started(_)
            | TimecodeEvent::Seeked { .. }
            | TimecodeEvent::Deleted(_) => {}
        }
    }

    for event in timeline_events.read() {
        match &event.command {
            TimelineCommand::StopTimeline(timeline_id) => {
                finish_timeline_ids.insert(*timeline_id);
                disable_timeline_ids.insert(*timeline_id);
            }
            TimelineCommand::SetTimelineRecording {
                timeline_id,
                enabled,
                target_track_id,
            } => {
                if !enabled
                    || recording_sessions.target_changed(*timeline_id, target_track_id.as_deref())
                {
                    finish_timeline_ids.insert(*timeline_id);
                }
                if !enabled {
                    disable_timeline_ids.insert(*timeline_id);
                }
            }
            _ => {}
        }
    }

    for event in timeline_actions.read() {
        if let TimelineAction::Stop(timeline_id) = event.action {
            finish_timeline_ids.insert(timeline_id);
            disable_timeline_ids.insert(timeline_id);
        }
    }

    for timeline_id in disable_timeline_ids {
        recording_states.disable(timeline_id);
    }

    for timeline_id in finish_timeline_ids {
        if let Some(session) = recording_sessions.take(timeline_id) {
            queue_recording_session_insert(timeline_id, session, &mut pending_actions);
        }
    }
}

/// Clear timeline-origin markers after recording has inspected this frame.
pub fn clear_timeline_command_origins(mut command_origins: ResMut<TimelineCommandOrigins>) {
    command_origins.clear();
}

#[cfg(test)]
mod tests {
    use bevy_app::prelude::*;
    use nightfall::prelude::{IdExpr, Identifiers};
    use nightfall_engine::prelude::{DataProvider, OperationId, PendingEngineActionBuffer, UndoId};
    use nightfall_timecode::TimecodeCommand;
    use nightfall_timecode::prelude::TimecodeGenerator;
    use nightfall_undo::prelude::{UndoManager, UndoRegistry};

    use super::*;
    use crate::prelude::{Timeline, Track};

    /// Wraps a timecode command with detached lifecycle context for recording tests.
    fn timecode_command(command: TimecodeCommand) -> TimecodeEvent {
        match command {
            TimecodeCommand::StartTimecode(id) => TimecodeEvent::Started(id),
            TimecodeCommand::PauseTimecode(id) => TimecodeEvent::Paused(id),
            TimecodeCommand::StopTimecode(id) => TimecodeEvent::Stopped(id),
            TimecodeCommand::SeekTimecode { id, position } => {
                TimecodeEvent::Seeked { id, position }
            }
            TimecodeCommand::DeleteTimecode(id) => TimecodeEvent::Deleted(id),
            TimecodeCommand::StoreTimecode(_) | TimecodeCommand::RenameTimecode { .. } => {
                panic!("CRUD commands are not runtime timecode events")
            }
        }
    }

    fn setup_recording_app() -> App {
        let mut app = App::new();
        app.add_message::<EngineActionEnvelope<ClipAction>>();
        app.add_message::<TimecodeEvent>();
        app.add_message::<CommandEnvelope<TimelineCommand>>();
        app.add_message::<EngineActionEnvelope<TimelineAction>>();
        app.init_resource::<TimelineRecordingStates>();
        app.init_resource::<TimelineRecordingSessions>();
        app.init_resource::<TimelineCommandOrigins>();
        app.init_resource::<PendingEngineActionBuffer>();
        app.init_resource::<UndoManager>();
        app.init_resource::<UndoRegistry>();
        app.insert_resource(DataProvider::<Timeline>::default());
        app.world_mut()
            .resource_mut::<UndoRegistry>()
            .register::<TimelineCommand>();
        app.world_mut()
            .resource_mut::<UndoRegistry>()
            .register_action::<TimelineAction>();
        app.add_systems(
            Update,
            (
                record_timeline_actions_system,
                finish_timeline_recording_sessions_system.after(record_timeline_actions_system),
            ),
        );
        app
    }

    fn spawn_clip(app: &mut App, id: u32, label: &str) -> Uuid {
        let uid = Uuid::new_v4();
        app.world_mut().spawn(Clip {
            identifiers: Identifiers {
                id,
                uid,
                label: label.to_string(),
            },
            source: None,
            ..Default::default()
        });
        uid
    }

    fn insert_active_timeline(app: &mut App, timeline_id: u32, tracks: Vec<Track>) -> Uuid {
        let timeline_uid = Uuid::new_v4();
        let mut timecode = TimecodeGenerator::default();
        timecode.timecode.identifiers.id = timeline_id;
        timecode.state.timecode_id = timeline_id;
        timecode.state.current_time = Duration::from_millis(1250);
        timecode.state.is_active = true;
        let timecode_uid = timecode.timecode.identifiers.uid;

        let timeline = Timeline {
            identifiers: Identifiers {
                id: timeline_id,
                uid: timeline_uid,
                label: format!("Timeline {}", timeline_id),
            },
            timecode_uid,
            tracks,
            ..Default::default()
        };
        app.world_mut()
            .resource_mut::<DataProvider<Timeline>>()
            .add(timeline.clone())
            .expect("timeline should store");

        let mut materialized = MaterializedTimeline::new(timeline);
        materialized.activate();
        app.world_mut().spawn(materialized);

        app.world_mut().spawn(timecode);

        timeline_uid
    }

    /// Stops or pauses recording and returns the queued internal persistence action.
    fn finish_recording_and_take_insert(
        app: &mut App,
        command: TimecodeCommand,
    ) -> Option<TimelineAction> {
        app.world_mut().write_message(timecode_command(command));
        app.update();

        let actions = app
            .world_mut()
            .resource_mut::<PendingEngineActionBuffer>()
            .drain();
        assert!(
            actions.len() <= 1,
            "recording stop should enqueue at most one action"
        );
        actions.into_iter().next().map(|action| {
            assert!(
                action.command_id.is_none(),
                "automatic recording persistence must not fabricate a user command"
            );
            assert!(
                action.undo_id.is_some(),
                "recording persistence should remain independently undoable"
            );
            *action
                .action
                .into_any()
                .downcast::<TimelineAction>()
                .expect("recording persistence should be a timeline action")
        })
    }

    /// Stops recording and returns the queued internal persistence action.
    fn stop_recording_and_take_insert(app: &mut App, timeline_id: u32) -> Option<TimelineAction> {
        finish_recording_and_take_insert(app, TimecodeCommand::StopTimecode(timeline_id))
    }

    #[test]
    fn records_start_clip_into_selected_track() {
        let mut app = setup_recording_app();
        let clip_uid = spawn_clip(&mut app, 7, "Key Light");
        insert_active_timeline(
            &mut app,
            42,
            vec![Track {
                id: "track-1".to_string(),
                label: "Track 1".to_string(),
                muted: false,
                solo: false,
                expanded: false,
                actions: Vec::new(),
                automation_lanes: Vec::new(),
            }],
        );
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(42, true, Some("track-1".to_string()));

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Start(
                IdExpr::Single(7),
            )));
        app.update();

        let command = stop_recording_and_take_insert(&mut app, 42)
            .expect("recording stop should enqueue recorded actions");
        let TimelineAction::InsertRecordedActions {
            timeline_id,
            track_id,
            actions,
        } = command
        else {
            panic!("expected recorded insert command");
        };
        assert_eq!(timeline_id, 42);
        assert_eq!(track_id, "track-1");
        assert_eq!(actions.len(), 1);
        let action = &actions[0];
        assert_eq!(action.position, Duration::from_millis(1250));
        assert!(matches!(
            action.action,
            ActionKind::StartClip(uid) if uid == clip_uid
        ));
    }

    #[test]
    fn drains_clip_events_when_recording_is_idle() {
        let mut app = setup_recording_app();
        spawn_clip(&mut app, 7, "Key Light");
        insert_active_timeline(
            &mut app,
            50,
            vec![Track {
                id: "track-1".to_string(),
                label: "Track 1".to_string(),
                muted: false,
                solo: false,
                expanded: false,
                actions: Vec::new(),
                automation_lanes: Vec::new(),
            }],
        );
        app.update();

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Start(
                IdExpr::Single(7),
            )));
        app.update();

        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(50, true, Some("track-1".to_string()));
        app.update();

        let preview_action_count = app
            .world()
            .resource::<TimelineRecordingSessions>()
            .sorted_previews()
            .iter()
            .map(|preview| preview.actions.len())
            .sum::<usize>();
        assert_eq!(
            preview_action_count, 0,
            "clip events emitted before recording starts should not be recorded later"
        );
        assert!(
            stop_recording_and_take_insert(&mut app, 50).is_none(),
            "stale clip events should not create a recorded insert"
        );
    }

    #[test]
    fn exposes_recording_session_preview_before_flush() {
        let mut app = setup_recording_app();
        let clip_uid = spawn_clip(&mut app, 8, "Preview Clip");
        insert_active_timeline(
            &mut app,
            49,
            vec![Track {
                id: "track-1".to_string(),
                label: "Track 1".to_string(),
                muted: false,
                solo: false,
                expanded: false,
                actions: Vec::new(),
                automation_lanes: Vec::new(),
            }],
        );
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(49, true, Some("track-1".to_string()));

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Start(
                IdExpr::Single(8),
            )));
        app.update();

        let previews = app
            .world()
            .resource::<TimelineRecordingSessions>()
            .sorted_previews();
        assert_eq!(previews.len(), 1);
        assert_eq!(previews[0].timeline_id, 49);
        assert_eq!(previews[0].target_track_id, "track-1");
        assert_eq!(previews[0].actions.len(), 1);
        assert!(matches!(
            previews[0].actions[0].action,
            ActionKind::StartClip(uid) if uid == clip_uid
        ));

        assert!(
            app.world()
                .resource::<PendingEngineActionBuffer>()
                .is_empty(),
            "recording preview should not enqueue the undoable insert before flush"
        );
    }

    #[test]
    fn removing_recording_session_discards_preview() {
        let mut sessions = TimelineRecordingSessions::default();
        sessions.append_actions(
            51,
            "track-1".to_string(),
            vec![Action {
                id: "recorded-1".to_string(),
                label: "Recorded".to_string(),
                position: Duration::from_millis(100),
                duration: Duration::from_millis(1000),
                action: ActionKind::StartClip(Uuid::new_v4()),
            }],
        );

        assert_eq!(sessions.sorted_previews().len(), 1);
        sessions.remove(51);
        assert!(sessions.sorted_previews().is_empty());
    }

    #[test]
    fn creates_recorded_actions_track_without_target() {
        let mut app = setup_recording_app();
        let clip_uid = spawn_clip(&mut app, 9, "Clip 9");
        insert_active_timeline(&mut app, 43, Vec::new());
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(43, true, None);

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Stop(
                IdExpr::Single(9),
            )));
        app.update();

        let command = stop_recording_and_take_insert(&mut app, 43)
            .expect("recording stop should enqueue recorded actions");
        let TimelineAction::InsertRecordedActions {
            track_id, actions, ..
        } = command
        else {
            panic!("expected recorded insert command");
        };
        assert!(track_id.starts_with("recorded-actions-"));
        assert_eq!(actions.len(), 1);
        assert!(matches!(
            actions[0].action,
            ActionKind::StopClip(uid) if uid == clip_uid
        ));
        let recording_states = app.world().resource::<TimelineRecordingStates>();
        assert_eq!(
            recording_states
                .get(43)
                .and_then(|state| state.target_track_id.as_deref()),
            Some(track_id.as_str())
        );
        assert!(
            !recording_states.get(43).is_some_and(|state| state.enabled),
            "stopping playback should disarm recording"
        );
    }

    #[test]
    fn records_into_selected_target_even_if_track_arrives_later() {
        let mut app = setup_recording_app();
        let clip_uid = spawn_clip(&mut app, 10, "Clip 10");
        insert_active_timeline(&mut app, 47, Vec::new());
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(47, true, Some("pending-record-target".to_string()));

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Start(
                IdExpr::Single(10),
            )));
        app.update();

        let command = stop_recording_and_take_insert(&mut app, 47)
            .expect("recording stop should enqueue recorded actions");
        let TimelineAction::InsertRecordedActions {
            track_id, actions, ..
        } = command
        else {
            panic!("expected recorded insert command");
        };
        assert_eq!(track_id, "pending-record-target");
        assert_eq!(actions.len(), 1);
        assert!(matches!(
            actions[0].action,
            ActionKind::StartClip(uid) if uid == clip_uid
        ));
    }

    #[test]
    fn ignores_timeline_originated_clip_actions() {
        let mut app = setup_recording_app();
        spawn_clip(&mut app, 11, "Clip 11");
        let timeline_uid = insert_active_timeline(&mut app, 44, Vec::new());
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(44, true, None);

        let undo_id = UndoId::new();
        let event = EngineActionEnvelope::with_context(
            OperationId::new(),
            None,
            Some(undo_id),
            ClipAction::Go(IdExpr::Single(11)),
        );
        app.world_mut()
            .resource_mut::<TimelineCommandOrigins>()
            .mark_clip_undo_id(undo_id.into());
        app.world_mut().write_message(event);
        app.update();

        {
            let timelines = app.world().resource::<DataProvider<Timeline>>();
            let timeline = timelines.get(timeline_uid).expect("timeline exists");
            assert!(
                timeline.tracks.is_empty(),
                "timeline-originated clip actions should not be recorded"
            );
        }
        assert!(
            stop_recording_and_take_insert(&mut app, 44).is_none(),
            "empty recording sessions should not enqueue insert commands"
        );
    }

    #[test]
    fn records_range_clip_expression_as_multiple_actions() {
        let mut app = setup_recording_app();
        let first_uid = spawn_clip(&mut app, 1, "One");
        let second_uid = spawn_clip(&mut app, 2, "Two");
        insert_active_timeline(&mut app, 45, Vec::new());
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(45, true, None);

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Go(
                IdExpr::Range { start: 1, end: 2 },
            )));
        app.update();

        let command = stop_recording_and_take_insert(&mut app, 45)
            .expect("recording stop should enqueue recorded actions");
        let TimelineAction::InsertRecordedActions { actions, .. } = command else {
            panic!("expected recorded insert command");
        };
        assert_eq!(actions.len(), 2);
        assert!(matches!(
            actions[0].action,
            ActionKind::AdvanceSequence(uid) if uid == first_uid
        ));
        assert!(matches!(
            actions[1].action,
            ActionKind::AdvanceSequence(uid) if uid == second_uid
        ));
    }

    #[test]
    fn pausing_playback_disarms_and_flushes_recording_session() {
        let mut app = setup_recording_app();
        let clip_uid = spawn_clip(&mut app, 12, "Clip 12");
        insert_active_timeline(
            &mut app,
            48,
            vec![Track {
                id: "track-1".to_string(),
                label: "Track 1".to_string(),
                muted: false,
                solo: false,
                expanded: false,
                actions: Vec::new(),
                automation_lanes: Vec::new(),
            }],
        );
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(48, true, Some("track-1".to_string()));

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Start(
                IdExpr::Single(12),
            )));
        app.update();

        let command =
            finish_recording_and_take_insert(&mut app, TimecodeCommand::PauseTimecode(48))
                .expect("recording pause should enqueue recorded actions");
        let TimelineAction::InsertRecordedActions {
            timeline_id,
            track_id,
            actions,
        } = command
        else {
            panic!("expected recorded insert command");
        };
        assert_eq!(timeline_id, 48);
        assert_eq!(track_id, "track-1");
        assert_eq!(actions.len(), 1);
        assert!(matches!(
            actions[0].action,
            ActionKind::StartClip(uid) if uid == clip_uid
        ));
        let recording_states = app.world().resource::<TimelineRecordingStates>();
        assert!(
            !recording_states.get(48).is_some_and(|state| state.enabled),
            "pausing playback should disarm recording"
        );
    }

    #[test]
    fn recording_session_insert_captures_one_undo_group() {
        let mut app = setup_recording_app();
        spawn_clip(&mut app, 7, "Key Light");
        insert_active_timeline(
            &mut app,
            46,
            vec![Track {
                id: "track-1".to_string(),
                label: "Track 1".to_string(),
                muted: false,
                solo: false,
                expanded: false,
                actions: Vec::new(),
                automation_lanes: Vec::new(),
            }],
        );
        app.world_mut()
            .resource_mut::<TimelineRecordingStates>()
            .set(46, true, Some("track-1".to_string()));

        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Start(
                IdExpr::Single(7),
            )));
        app.update();
        app.world_mut()
            .write_message(EngineActionEnvelope::detached(ClipAction::Stop(
                IdExpr::Single(7),
            )));
        app.update();
        app.world_mut()
            .write_message(timecode_command(TimecodeCommand::StopTimecode(46)));
        app.update();

        nightfall_undo::dispatcher::process_pending_actions(app.world_mut());
        app.world_mut()
            .resource_mut::<UndoManager>()
            .finalize_detached_groups();

        let undo_manager = app.world().resource::<UndoManager>();
        assert_eq!(undo_manager.undo_depth(), 1);
        let group = undo_manager
            .peek_undo()
            .expect("recorded insert should create an undo group");
        assert_eq!(group.entries.len(), 1);

        let inverse = group.entries[0]
            .command
            .as_any()
            .downcast_ref::<TimelineCommand>()
            .expect("inverse should be a timeline command");
        let TimelineCommand::StoreTimeline(timeline) = inverse else {
            panic!("expected store timeline inverse");
        };
        assert_eq!(timeline.identifiers.id, 46);
        let track = timeline
            .tracks
            .iter()
            .find(|track| track.id == "track-1")
            .expect("original target track should be restored");
        assert!(track.actions.is_empty());
    }
}
