// SPDX-License-Identifier: MPL-2.0

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

//! Empty crate whose `Cargo.toml` is generated by `cargo hakari`.
//!
//! Every workspace crate depends on it for native targets, so Cargo enables one
//! union of third-party dependency features no matter which crates a command
//! selects. See `CONTRIBUTING.md` for how to regenerate it.
