[package]
name = "nightfall-timeline"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true, features = ["multipart"], optional = true }
bevy_app.workspace = true
bevy_diagnostic.workspace = true
bevy_ecs.workspace = true
moonshine-kind.workspace = true
nightfall = { path = "../common" }
nightfall-actions = { path = "../actions" }
nightfall-audio = { path = "../audio", optional = true }
nightfall-cmd-parse = { path = "../cmd-parse" }
nightfall-compositor = { path = "../compositor" }
nightfall-cues = { path = "../cues" }
nightfall-desk = { path = "../desk", default-features = false }
nightfall-dmx = { path = "../dmx" }
nightfall-engine = { path = "../engine" }
nightfall-clips = { path = "../clips" }
nightfall-fixtures = { path = "../fixtures" }
nightfall-fx = { path = "../fx" }
nightfall-lookahead = { path = "../lookahead" }
nightfall-playback-planner = { path = "../playback-planner" }
nightfall-instances = { path = "../instances" }
nightfall-selection = { path = "../selection" }
nightfall-timecode = { path = "../timecode" }
nightfall-undo = { path = "../undo" }
nightfall-websocket = { path = "../websocket", optional = true }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
typeshare.workspace = true
uuid.workspace = true
web-time.workspace = true

[features]
audio = ["dep:nightfall-audio"]
http = ["dep:axum", "dep:nightfall-websocket"]

[dev-dependencies]
criterion.workspace = true
minicbor-serde.workspace = true
nightfall-fixture-model = { path = "../fixture-model" }
nightfall-flow = { path = "../flow" }
nightfall-fx-module = { path = "../fx-module" }

[[bench]]
name = "planner"
harness = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nightfall-workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
