#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { nightfallTestDataDir } from "./nightfall-test-data-dir.mjs";
import { sharedBrowsersPath } from "./playwright-path.mjs";
import { resolveMainWorktree } from "./worktree-data-dir.mjs";

/**
 * Returns a random local backend port in the development range.
 */
function randomPort() {
  return 3000 + Math.floor(Math.random() * 1000);
}

const ASSIGNMENT_KEY = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/u;

/**
 * Preserves inherited dotenv text while applying worktree-specific overrides.
 *
 * An overridden key keeps the position of its first assignment in the seed,
 * later assignments of that key are dropped, and keys absent from the seed are
 * appended, so rerunning setup never accumulates duplicate keys.
 */
export function buildEnvLines({ port, projectRoot, mainWorktree, seed = "" }) {
  const overrides = new Map([
    ["NIGHTFALL_PORT", String(port)],
    ["PLAYWRIGHT_BROWSERS_PATH", sharedBrowsersPath],
  ]);

  if (mainWorktree && mainWorktree !== projectRoot) {
    overrides.set("NIGHTFALL_DATA_DIR", nightfallTestDataDir(projectRoot));
    overrides.set("NIGHTFALL_OUTPUT_SACN_ENABLED", "false");
    overrides.set("NIGHTFALL_OUTPUT_ARTNET", "false");
    overrides.set("NIGHTFALL_INPUT_SACN_ENABLED", "false");
    overrides.set("NIGHTFALL_INPUT_ARTNET", "false");
  }

  const written = new Set();
  const envLines = [];
  for (const line of seed ? seed.trimEnd().split(/\r?\n/u) : []) {
    const key = line.match(ASSIGNMENT_KEY)?.[1];
    if (!key || !overrides.has(key)) {
      envLines.push(line);
    } else if (!written.has(key)) {
      envLines.push(`${key}=${overrides.get(key)}`);
      written.add(key);
    }
  }
  for (const [key, value] of overrides) {
    if (!written.has(key)) envLines.push(`${key}=${value}`);
  }

  return envLines;
}

/**
 * Writes worktree-local environment and Cargo config files.
 */
async function main() {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const projectRoot = dirname(scriptDir);
  const envFile = join(projectRoot, ".env");
  const mainWorktree = await resolveMainWorktree(projectRoot);
  let seed = "";
  try {
    seed = await readFile(join(mainWorktree || projectRoot, ".env"), "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }

  const portRaw = process.env.NIGHTFALL_PORT?.trim();
  const port =
    portRaw && Number.isFinite(Number(portRaw))
      ? Number.parseInt(portRaw, 10)
      : randomPort();
  const envLines = buildEnvLines({ port, projectRoot, mainWorktree, seed });

  await writeFile(envFile, `${envLines.join("\n")}\n`, "utf8");
  process.stdout.write(
    `OK: Generated ${envFile} with NIGHTFALL_PORT=${port}\n`,
  );

  const cargoDir = join(process.cwd(), ".cargo");
  const cargoFile = join(cargoDir, "config.toml");
  await mkdir(cargoDir, { recursive: true });
  await writeFile(
    cargoFile,
    "# Autogenerated by hook. Do not edit.\n[unstable]\ntrim-paths = true\n",
    "utf8",
  );
  process.stdout.write(`OK: Generated ${cargoFile}\n`);
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`${message}\n`);
    process.exit(1);
  });
}
