[package]
name = "nightfall-scene-objects"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
nightfall = { path = "../common" }
nightfall-engine = { path = "../engine" }
nightfall-fixtures = { path = "../fixtures" }
nightfall-undo = { path = "../undo" }
serde.workspace = true
serde_json.workspace = true
smart-default.workspace = true
strum.workspace = true
typeshare.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
