[package]
name = "nightfall-output-artnet"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
artnet_protocol.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
nightfall-desk = { path = "../desk" }
nightfall-dmx = { path = "../dmx" }
nightfall-engine = { path = "../engine" }
nightfall-fixtures = { path = "../fixtures" }
nightfall-io = { path = "../io" }
nightfall-service-host = { path = "../service_host" }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
