[package]
name = "nightfall-showfile"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bevy_ecs.workspace = true
moonshine-kind.workspace = true
nightfall = { path = "../common" }
nightfall-cues = { path = "../cues" }
nightfall-desk = { path = "../desk", default-features = false }
nightfall-dmx = { path = "../dmx" }
nightfall-engine = { path = "../engine" }
nightfall-clips = { path = "../clips" }
nightfall-fixtures = { path = "../fixtures" }
nightfall-flow = { path = "../flow", default-features = false }
nightfall-fx = { path = "../fx" }
nightfall-input-midi = { path = "../input_midi", optional = true }
nightfall-input-osc = { path = "../input_osc", optional = true }
nightfall-io = { path = "../io" }
nightfall-scene-objects = { path = "../scene-objects" }
nightfall-selection = { path = "../selection" }
nightfall-timecode = { path = "../timecode" }
nightfall-timeline = { path = "../timeline", default-features = false }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true

[features]
default = []
midi = ["dep:nightfall-input-midi"]
osc = ["dep:nightfall-input-osc"]

[lints]
workspace = true
